Navbar
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #11
Opened 2019-12-06 16:20 UTC by philamwild

2019-12-06 17:06 UTC, TheoBoschetti requested changes

2019-12-06 17:06 UTC, TheoBoschetti commented on frontend/src/App.scss
> +  padding: 0;
is it not already in reset.css ?

2019-12-06 17:06 UTC, TheoBoschetti commented on frontend/src/components/Navbar.jsx
> +  const [menuIsOpen, setOpen] = useState(false);
[IsMenuopen, setIsMenuOpen]

2019-12-06 17:06 UTC, TheoBoschetti commented on frontend/src/components/Navbar.jsx
> +          <h1>TETATETE</h1>
We already have a h1 markup in component tagline

2019-12-06 17:06 UTC, TheoBoschetti commented on frontend/src/components/Navbar.jsx
> +          <p>tttt</p>
It will be a img here imo

2019-12-11 10:25 UTC, LoicBrassart commented on frontend/src/components/Navbar.jsx
> +          <h1>TETATETE</h1>
More than that, please remember to not write the final website name in your code anymore

2019-12-11 10:27 UTC, LoicBrassart approved these changes
SnE

2019-12-12 11:02 UTC, closed without merging