Form login
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #43
Opened 2020-01-16 10:27 UTC by LeoDiduch

2020-01-16 19:42 UTC, TheoBoschetti requested changes

2020-01-16 19:42 UTC, TheoBoschetti commented on frontend/src/components/FormCreateCause.jsx
> +    console.log(data);
Console log

2020-01-16 19:42 UTC, TheoBoschetti commented on frontend/src/components/FormCreateCause.jsx
> +        console.log(`Booyah! ${res.data}`);
console log

2020-01-16 19:42 UTC, TheoBoschetti commented on frontend/src/components/FormCreateCause.jsx
> +        console.log(`Nay! ${err}`);
An alerte should be better

2020-01-20 08:48 UTC, TheoBoschetti submitted a review, later dismissed
ok

2020-01-20 13:24 UTC, BastienSaulnier submitted a review, later dismissed
SnE

2020-01-22 07:29 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-01-22 09:20 UTC, BastienSaulnier approved these changes
SnE

2020-01-22 16:19 UTC, LoicBrassart approved these changes
SnE

2020-01-22 16:19 UTC, merged