Mods amb infos
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #57
Opened 2020-01-20 14:54 UTC by BastienSaulnier

2020-01-20 14:55 UTC, LeoDiduch submitted a review, later dismissed
SnE

2020-01-21 15:23 UTC, LoicBrassart requested changes
No. More. Placeholders.
Ever.

2020-01-21 15:23 UTC, LoicBrassart commented on frontend/src/pages/AmbassadorInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
No. More. Placeholders.
Ever.

2020-01-21 15:23 UTC, LoicBrassart commented on frontend/src/pages/AmbassadorInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
No. More. Placeholders.
Ever.

2020-01-21 15:23 UTC, LoicBrassart commented on frontend/src/pages/AmbassadorInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
No. More. Placeholders.
Ever.

2020-01-21 15:23 UTC, LoicBrassart commented on frontend/src/pages/CauseInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
No. More. Placeholders.
Ever.

2020-01-21 15:23 UTC, LoicBrassart commented on frontend/src/pages/CauseInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
No. More. Placeholders.
Ever.

2020-01-21 15:23 UTC, LoicBrassart commented on frontend/src/pages/CauseInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
No. More. Placeholders.
Ever.

2020-01-21 18:21 UTC, LeoDiduch commented on frontend/src/pages/AmbassadorInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
need other branch to add good src

2020-01-21 18:21 UTC, LeoDiduch commented on frontend/src/pages/AmbassadorInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
need other branch to add good src

2020-01-21 18:22 UTC, LeoDiduch commented on frontend/src/pages/AmbassadorInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
need other branch to add good src

2020-01-21 18:22 UTC, LeoDiduch commented on frontend/src/pages/CauseInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
need other branch to add good src

2020-01-21 18:22 UTC, LeoDiduch commented on frontend/src/pages/CauseInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
need other branch to add good src

2020-01-21 18:22 UTC, LeoDiduch commented on frontend/src/pages/CauseInfos.jsx
> +                  src="https://via.placeholder.com/50x50"
need other branch to add good src

2020-01-21 18:25 UTC, LeoDiduch submitted a review, later dismissed
SnE, placeHolder change when pull request with backend routes is completed

2020-01-22 16:26 UTC, LeoDiduch approved these changes
SnE

2020-01-23 11:51 UTC, LoicBrassart approved these changes
SnE

2020-01-23 13:10 UTC, merged