Component footer
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #6
Opened 2019-12-06 13:41 UTC by LeoDiduch

2019-12-06 16:24 UTC, BastienSaulnier requested changes
Fix the few things in code layout please :)

2019-12-06 16:24 UTC, BastienSaulnier commented on frontend/src/components/Footer.jsx
> +    <div id="footerContainer">
Replace id by className="Footer" please

2019-12-06 16:24 UTC, BastienSaulnier commented on frontend/src/components/Footer.jsx
> +          <img src="" alt="Fcb" />
replace Fcb by Facebook please

2019-12-06 16:24 UTC, BastienSaulnier commented on frontend/src/components/Footer.jsx
> +          <img src="" alt="Insta" />
Replace Insta by Instragram please

2019-12-06 16:24 UTC, BastienSaulnier commented on frontend/src/components/styles/Footer.scss
> +#footerContainer {
replace # by . please and footerContainer by Footer

2019-12-06 16:24 UTC, BastienSaulnier commented on frontend/src/components/styles/Footer.scss
> +  > #rightContainer {
useless rightContainer call because you call it after in your rules

2019-12-06 16:24 UTC, BastienSaulnier commented on frontend/src/components/styles/Footer.scss
> +}
clean a bit your rules off useless space between rules please :)

2019-12-06 16:58 UTC, BastienSaulnier submitted a review, later dismissed
Saw no evil now

2019-12-11 10:22 UTC, LoicBrassart submitted a review, later dismissed
SnE

2019-12-13 10:35 UTC, BastienSaulnier approved these changes
SnE

2019-12-16 10:02 UTC, LoicBrassart approved these changes
SnE

2019-12-16 10:21 UTC, merged