Mods campaign by
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #61
Opened 2020-01-21 16:54 UTC by BastienSaulnier

2020-01-21 17:02 UTC, LeoDiduch submitted a review, later dismissed
SnE

2020-01-22 08:27 UTC, LoicBrassart requested changes
There's a typo, fix it quickly and notify me on Slack

2020-01-22 08:27 UTC, LoicBrassart commented on frontend/src/pages/CampaignInfos.jsx
> +            <button>{campaignInfo.value3}</button>
"value2", isn't it ?

2020-01-22 08:41 UTC, BastienSaulnier commented on frontend/src/pages/CampaignInfos.jsx
> +            <button>{campaignInfo.value3}</button>
Yep, you are right, my bad

2020-01-22 08:51 UTC, LoicBrassart approved these changes
SnE

2020-01-22 08:51 UTC, LoicBrassart commented on frontend/src/App.js
> +
Why is this file touched ? 
And why is there a second empty line ? It seems to indicate that your Prettier doesn't work on `.js` files

2020-01-22 08:56 UTC, LeoDiduch approved these changes
SnE

2020-01-22 08:57 UTC, merged