Private route
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #85
Opened 2020-01-27 16:56 UTC by LeoDiduch

2020-01-27 17:02 UTC, BastienSaulnier submitted a review, later dismissed
SnE

2020-01-28 10:41 UTC, BastienSaulnier submitted a review, later dismissed
SnE

2020-01-28 15:20 UTC, LoicBrassart requested changes

2020-01-28 15:20 UTC, LoicBrassart commented on frontend/src/components/FormLoginBO.jsx
> +        dispatch({ type: "JWT", value: res.data.token });
(Generally speaking, we would `dispatch` only once, giving an object)

2020-01-28 15:20 UTC, LoicBrassart commented on frontend/src/pages/HomeBO.jsx
> +      <FormCreateUser />}
Why this bracket ?

2020-01-28 15:20 UTC, LoicBrassart commented on frontend/src/redux/reducers/reducer.js
> +    case "SUPERADMIN":
... And that's why we dispaatch only once, generally speaking

2020-01-28 15:34 UTC, LeoDiduch commented on frontend/src/pages/HomeBO.jsx
> +      <FormCreateUser />}
sorry :+1:

2020-01-28 15:49 UTC, BastienSaulnier approved these changes
SnE

2020-01-31 09:18 UTC, LoicBrassart approved these changes
SnE

2020-01-31 09:20 UTC, merged