Redux refactor
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #87
Opened 2020-01-28 14:38 UTC by BastienSaulnier

2020-01-28 14:50 UTC, LeoDiduch submitted a review, later dismissed
SnE

2020-01-28 15:26 UTC, LoicBrassart requested changes
Question

2020-01-28 15:26 UTC, LoicBrassart commented on frontend/src/components/NavBar.jsx
> +              onClick={() => dispatch({ type: "SWITCH", payload: null })}
Why do you specify `null` payloads ?

2020-01-28 17:04 UTC, BastienSaulnier commented on frontend/src/components/NavBar.jsx
> +              onClick={() => dispatch({ type: "SWITCH", payload: null })}
Done

2020-01-28 17:05 UTC, LeoDiduch submitted a review, later dismissed
SnE

2020-01-31 09:18 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-01-31 09:26 UTC, LeoDiduch approved these changes
SnE

2020-01-31 09:29 UTC, LoicBrassart approved these changes
SnE

2020-01-31 09:31 UTC, merged