Fix bug donation
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #88
Opened 2020-01-28 15:17 UTC by LeoDiduch

2020-01-28 16:40 UTC, BastienSaulnier approved these changes

2020-01-31 09:03 UTC, BastienSaulnier submitted a review, later dismissed
SnE

2020-01-31 09:22 UTC, LoicBrassart requested changes
Left a better writing for a bit of code

2020-01-31 09:22 UTC, LoicBrassart commented on frontend/src/pages/CampaignInfos.jsx
> +          )}
```
{
    donor.donation_value>0 && 
    <p>A hauteur de <span>{donor.donation_value} €</span> !
}
```

2020-01-31 09:32 UTC, LeoDiduch commented on frontend/src/pages/CampaignInfos.jsx
> +          )}
Ok change this right now

2020-01-31 09:42 UTC, BastienSaulnier approved these changes
SnE changes were made

2020-01-31 09:57 UTC, LoicBrassart approved these changes
SnE

2020-01-31 10:05 UTC, merged