Update of error messages
WildCodeSchool/lille-0919-js-projet3-tootasty pull request #89
Opened 2020-01-28 15:41 UTC by TheoBoschetti

2020-01-28 15:47 UTC, BastienSaulnier submitted a review, later dismissed
SnE

2020-01-31 09:27 UTC, LoicBrassart requested changes
Minor suggestions

2020-01-31 09:27 UTC, LoicBrassart commented on backend/routes/ambassador.js
> +                      "Erreur lors de la modification de l'ambassadeur." + err
For consistency's sake, don't send `err` there

2020-01-31 09:27 UTC, LoicBrassart commented on backend/routes/association.js
> +                      "Erreur lors de la modification de l'association." + err
Same

2020-01-31 09:27 UTC, LoicBrassart commented on backend/routes/auth.js
> +    if (err) return res.status(500).send("Erreur lors de la connection.");
"connexion" en Français

2020-01-31 09:27 UTC, LoicBrassart commented on backend/routes/campaign.js
> +              .send("Erreur lors de la création de la campagne." + err);
Don't send `err`

2020-01-31 09:39 UTC, BastienSaulnier approved these changes
SnE anymore ( sorry for my blindness about err display... )

2020-01-31 09:57 UTC, LoicBrassart approved these changes
SnE

2020-01-31 10:04 UTC, merged